export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';

export const GET_POSTS_REQ = 'GET_POSTS_REQ';

export const GET_POSTS_SUC = 'GET_POSTS_SUC';

export const GET_POSTS_FAI = 'GET_POSTS_FAI';

export const SEND_FILTER_TEXT = 'SEND_FILTER_TEXT';

export const MODAL_IS_OPEN = 'MODAL_IS_OPEN';

export const TOGGLE_MODAL_IS_OPEN = 'TOGGLE_MODAL_IS_OPEN';

export const SAVE_HOTEL_DATA = 'SAVE_HOTEL_DATA';